version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-unit:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm run test:unit:ci

  test-integration:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run integration tests
          command: npm run test:integration:ci

  build:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build

workflows:
  test-and-build:
    jobs:
      - test-unit
      - test-integration
      - build:
          requires:
            - test-unit
            - test-integration
