version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  test-unit:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Unit Tests
          command: npm run test:unit:ci
      - store_test_results:
          path: test-results

  test-integration:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Integration Tests
          command: npm run test:integration:ci

  build:
    executor:
      name: node/default
      tag: '24.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Application
          command: npm run build

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-integration
      - test-unit
      - build:
          requires:
            - test-integration
            - test-unit
